### ISSUE TITLE
driver

### ISSUE THREAD

**Issue by ArcticWarrior699** [singhhdev/cs2-external-source-kernel#1]
please release a compiled version of the driver .sys as i am having issues with some librarys even after troubleshooting i do have the sdk and wdk etc.

**Comment by singhhdev** [comment]
Hi, you can download the compiled driver at :
https://www.unknowncheats.me/forum/counter-strike-2-releases/605274-kernel-csgo-source-exteral.html

i did not want to put any binaries on github etc. but you can download from there the driver, it also comes with a mapper!
