### ISSUE TITLE
ImGui menu problem disappearing

### ISSUE THREAD

**Issue by skhrlx** [singhhdev/cs2-external-source-kernel#10]
Currently, I'm trying to fix the menu problem.

What i got for now:

1. The cheat is working (I forced BHOP true, and it's bhopping)
2. The nazi crosshair is rendering + aimbot fov circle
3. I updated the cheat Offsets:: with the latest offsets from a2x dumper (debugging the results from the offsets, all seems fine to me)
4. I saw that you set some manual offsets, like on_ground

Why the menu doesn't show 🤡 I gonna keep reading the source

**Comment by urfavmonkeycheats** [comment]
can u add me on discord 48.i

**Comment by skhrlx** [comment]
> can u add me on discord 48.i

I sent

**Comment by singhhdev** [comment]
make the game windowed first like a small box, then load cheat, then make it into fullscreenw windowed.

to fix in the code: make the MyWnd TOPMOST so it is displayed on the whole window instead of cs, i made this to bypass the overlay detection flags
