### ISSUE TITLE
Test-signing mode gives error 577 when trying to start the driver

### ISSUE THREAD

**Issue by altatF12** [singhhdev/cs2-external-source-kernel#11]
Even with test mode, i can't initialize the driver

**Comment by skhrlx** [comment]
The driver has been made to Initialize with an mapper, his entry point doesn't support the normal start with test mode

**Comment by altatF12** [comment]
The problem is that I've tried using kdmapper but I compile it. I tried using the pre-compiled one but it gives Device/Nal already in use (And yes, i already tried using NalFix but it shows up [-] Driver not found)
So I can't even use it

**Comment by singhhdev** [comment]
download the already compiled kdmapper for you from https://www.unknowncheats.me/forum/downloads.php?do=file&id=42286

**Comment by altatF12** [comment]
Bro
That's literally the one that i downloaded
It just doesn't work
