### ISSUE TITLE
UCMapper BSOD

### ISSUE THREAD

**Issue by Eval0** [singhhdev/cs2-external-source-kernel#12]
I can't use kdmapper, I get the following error anyway
[<] Loading vulnerable driver, Name: qWcOjNIScWXoTQCAhYF
[+] NtLoadDriver Status 0x0
[+] PiDDBLock Ptr 0xfffff80153367f18
[+] PiDDBCacheTable Ptr 0xfffff80153368054
[-] Failed to map IO space of 0x000000000000000000000000
[-] Can't lock PiDDBCacheTable
[-] Failed to ClearPiDDBCacheTable

About the UCMapper Github repository:https://github.com/MmMapIoSpace/UCMapper

**Comment by KoiHooks** [comment]
Did you kdmapper as admin?

**Comment by Eval0** [comment]
> Did you kdmapper as admin?

yep
