### ISSUE TITLE
Smoth, rcs.

### ISSUE THREAD

**Issue by LPATAN1** [singhhdev/cs2-external-source-kernel#17]
Smoth and RCS not working, Smoth when you up more than 1, the camera shakes when you try to aim someone, and RCS still not visible, with some checkbox, but in game notworkin if is ON.
pd: nice relase

**Comment by LPATAN1** [comment]
Working now, thanks for de update and fix. But i think RCS not working tried some configs and nothing, but all other options are ok.

**Comment by singhhdev** [comment]
try again now, fixed

**Comment by LPATAN1** [comment]
i think soruce not updated, same files of 17h ago.
