### ISSUE TITLE
Build solution error

### ISSUE THREAD

**Issue by DeboogerToDebuga** [singhhdev/cs2-external-source-kernel#18]
I cant build a  solution 
![Screenshot_15](https://github.com/singhhdev/cs2-external-source-kernel/assets/79271872/27e60b09-8634-455c-b323-e7d7222abd63)

**Comment by zuqr** [comment]
im getting this too

**Comment by singhhdev** [comment]
delete the if condition statement and try again, you need to include a library. do a simple google search
