### ISSUE TITLE
Cheat closes fastly 

### ISSUE THREAD

**Issue by Rolesional** [singhhdev/cs2-external-source-kernel#4]
i compiled driver and cheat but cheat closing fast or idk: The cheat menu appears and shrinks and disappears.
and console hides 
can u help me? my discord: rolesional

**Comment by singhhdev** [comment]
Yes, make your game windowed first not fullscreen windowed but windowed. then you can make it fullscreen windowed and the cheat will show up. Make sure you press "end" on your keyboard so the cheat can close

**Comment by singhhdev** [comment]
Follow these steps:

- press end on your keyboard first to stop the cheat
- make game windowed
- run the cheat again and it will work!

**Comment by Preposi** [comment]
I have the same problem actually. Tried the steps you mentioned, but didn't work. Here's a screenshot of the cheat before it closes.
![image](https://github.com/singhhdev/cs2-external-source-kernel/assets/138894034/0474668c-02e0-4744-ace4-bab8a4b30e05)

**Comment by Rolesional** [comment]
ty i maked this cheat undetected btw

**Comment by Rolesional** [comment]
read only + kernel = undetected
ty for source

**Comment by Rolesional** [comment]
and how can i delete team check and esp limit? (For casual and deathmatch)

**Comment by ghastlytim** [comment]
> m actually. Tried the steps you mentioned, but didn't work. Here's a screenshot of the cheat before it closes.

not true can be detected but valve is ass also "read only" ????? if u check where the features like glow and other things are its writing to game mem sir
