### ISSUE TITLE
Errors compile

### ISSUE THREAD

**Issue by Guilherme120** [singhhdev/cs2-external-source-kernel#5]
I'm having several problems compiling the cheat, can you give me your discord?

**Comment by Guilherme120** [comment]
my discord: .lw.

**Comment by singhhdev** [comment]
Which errors are you getting?

post a screenshot here

**Comment by Guilherme120** [comment]
![image](https://github.com/singhhdev/cs2-external-source-kernel/assets/45338369/b2082b96-ff8c-49ac-8c6a-608f9ea2901e)
![image](https://github.com/singhhdev/cs2-external-source-kernel/assets/45338369/bbad94b3-2814-4149-923b-62d56851da64)
![image](https://github.com/singhhdev/cs2-external-source-kernel/assets/45338369/09be2016-8995-4478-aa65-bfd965aad304)
These are the errors that I don't know how to solve, I'm still a beginner

**Comment by sfmax54** [comment]
> ![image](https://user-images.githubusercontent.com/45338369/277182079-b2082b96-ff8c-49ac-8c6a-608f9ea2901e.png) ![image](https://user-images.githubusercontent.com/45338369/277182090-bbad94b3-2814-4149-923b-62d56851da64.png) ![image](https://user-images.githubusercontent.com/45338369/277182100-09be2016-8995-4478-aa65-bfd965aad304.png) These are the errors that I don't know how to solve, I'm still a beginner

Same here
