### ISSUE TITLE
Compiling help

### ISSUE THREAD

**Issue by Kimnzzz** [singhhdev/cs2-external-source-kernel#6]
When compiling the driver i get 
![image](https://github.com/singhhdev/cs2-external-source-kernel/assets/44318930/627983a7-f45f-4de5-9afe-755f3985f445)
Is that correct way? what do i do then after that.

When compiling the usermode i get
![image](https://github.com/singhhdev/cs2-external-source-kernel/assets/44318930/970ea5fd-07ad-4a0b-8580-500ad25a4d9a)
What did I do wrong there?

**Comment by Rolesional** [comment]
get the render.hpp's directory and paste it to "#include " *here* and add \render.hpp" it will be fixed

**Comment by CRaZe1784** [comment]
I managed to run the cheat, however when i did run the menu instantly squashed into in existence. How do i fix this?

**Comment by Kimnzzz** [comment]
> get the render.hpp's directory and paste it to "#include " _here_ and add \render.hpp" it will be fixed

Thank you brother, my bad didn't read the error thoroughly. Know I have the cmd window disappearing problem.
