### ISSUE TITLE
Used compiled file of 22h2, cheat doesnt work

### ISSUE THREAD

**Issue by virenkk** [singhhdev/cs2-external-source-kernel#7]
I downloaded 22h2 version from UC. 
Driver was loaded successfully from cmd.
After that I ran the cs2 esp file. Started cs2 in windowed and changed to fullscreen.|
The menu of cheat popped up;however, the cheats were not working. selected and deselected esp box / snap/ none of them were working. 
any help?

**Comment by zuqr** [comment]
me too non of the features working for me

**Comment by urfavmonkeycheats** [comment]
add me on discord 48.i

**Comment by virenkk** [comment]
> 48.i

sent a request from frosty93

**Comment by virenkk** [comment]
i was told to update the entry.cpp file with 0x71558 .. I did but I am not able to compile

Severity Code Description Project File Line Suppression State
Error (active) E0020 identifier "PEPROCESS" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\utils.h 210
Error (active) E1696 cannot open source file "ntifs.h" Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\imports.h 5
Error (active) E1696 cannot open source file "ntddk.h" Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\imports.h 6
Error (active) E1696 cannot open source file "ntimage.h" Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\imports.h 8
Error (active) E1696 cannot open source file "ntstrsafe.h" Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\imports.h 10
Error (active) E0020 identifier "POBJECT_TYPE" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\defines.h 248
Error (active) E0020 identifier "PCLIENT_ID" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\defines.h 250
Error (active) E0145 variable "PsGetProcessPeb" may not be initialized Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\defines.h 252
Error (active) E0020 identifier "PEPROCESS" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\defines.h 252
Error (active) E0020 identifier "PACCESS_STATE" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\defines.h 255
Error (active) E0020 identifier "POBJECT_TYPE" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\defines.h 255
Error (active) E0020 identifier "KPROCESSOR_MODE" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\defines.h 255
Error (active) E0020 identifier "DbgPrintEx" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\entry.cpp 9
Error (active) E0020 identifier "STATUS_FAILED_DRIVER_ENTRY" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\entry.cpp 10
Error (active) E0020 identifier "STATUS_SUCCESS" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\entry.cpp 19
Error (active) E0020 identifier "PEPROCESS" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\utils.h 99
Error (active) E0020 identifier "PEPROCESS" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\utils.h 187
Error (active) E0020 identifier "PEPROCESS" is undefined Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\utils.h 238
Error C1083 Cannot open include file: 'ntifs.h': No such file or directory Kernel E:\external\cheat source_[unknowncheats.me]_\cheat source\driver\Kernel\imports.h 5
