### ISSUE TITLE
I managed to run the cheat, however when i did run the menu instantly squashed into in existence. How do i fix this?

### ISSUE THREAD

**Issue by CRaZe1784** [singhhdev/cs2-external-source-kernel#9]
I was able to successfully compiling it, I managed to open whilst following instructions on how to run it, however i came into an issue where the menu would instantly go away. How could i fix this?

**Comment by zuqr** [comment]
me too

**Comment by singhhdev** [comment]
make the game windowed first, like a small box, then make it fullscreen windowed.

**Comment by zuqr** [comment]
i did, it still doesnt work
